---
- hosts: vagrant
  user: vagrant 
  sudo: True
  vars_files:
    - config.yml
    - tuning.yml

  tasks:
    - include: roles/site-deployment/tasks/tasks-archive.yml

  handlers: 
    - include: roles/nginx/handlers/main.yml
    - include: roles/php-fpm/handlers/main.yml
