---      
- name: install ssmtp
  apt: name=ssmtp state=installed

- name: configure ssmtp
  template: src=etc-ssmtp-ssmtp.conf.j2
            dest=/etc/ssmtp/ssmtp.conf
  # notify: 
  #   - restart ssmtp
