---   
# This loads faster if you comment out the first three and just run the apt install.
# But it doesn't work on Digital Ocean for some reason. It has the precise universe repo
# but doesn't see this package, whereas it works on VirtualBox

  - name: install fireball
    apt: name=$item state=installed    
    with_items: 
      - python
      - python-dev
      - python-setuptools
      - python-keyczar
      - python-zmq
      - build-essential

  - name: start fireball
    action: fireball
           
  # - name: install fireball
  #   apt: name=ansible-node-fireball state=installed
